version: "3.9"

services:
  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"

  postgres_database:
    image: postgres
    container_name: postgres_database
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: on-failure

  redis_database:
    image: redis
    container_name: redis_database
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    restart: on-failure