"""empty message

Revision ID: 1b29a7e5159f
Revises: 0ee48f1b55a8
Create Date: 2022-09-01 23:38:30.747732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b29a7e5159f'
down_revision = '0ee48f1b55a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_categories_category_id_fkey', 'questions_categories', type_='foreignkey')
    op.create_foreign_key(None, 'questions_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions_categories', type_='foreignkey')
    op.create_foreign_key('questions_categories_category_id_fkey', 'questions_categories', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
