"""empty message

Revision ID: 4f8d1899078b
Revises: dbe4b4161476
Create Date: 2022-09-07 00:20:14.703492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d1899078b'
down_revision = 'dbe4b4161476'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['answer_text'])
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'questions', ['question_text'])
    op.create_unique_constraint(None, 'quizzes', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='unique')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
