"""empty message

Revision ID: a4b92ac272ff
Revises: 4f8d1899078b
Create Date: 2022-09-08 18:52:02.397985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b92ac272ff'
down_revision = '4f8d1899078b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_results_user_email_key', 'quiz_results', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('quiz_results_user_email_key', 'quiz_results', ['user_email'])
    # ### end Alembic commands ###
